fix: исправить типы проекта
gpn-prototypes/vega-sp pull request #114
Opened 2020-12-17 11:41 UTC by Inzephirum

## Описание изменений
https://jira.konakov.tv/browse/VEGA-2144

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: есть описание изменений или приложена ссылка на задачу с описанием, оставлены пояснительные комментарии к diff
- [ ] JS: нет предупреждений и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем PR
- [ ] Коммиты: проименованы в соответствии с [правилами](../docs/commits-style.md)

2020-12-17 11:57 UTC, c1n1k approved these changes

2020-12-18 07:14 UTC, fixmylie approved these changes

2020-12-18 07:57 UTC, maksim-kononov-csssr requested changes

2020-12-18 07:57 UTC, maksim-kononov-csssr commented on src/pages/project/EditProjectPage.tsx
> +    yearStart: project.yearStart ?? new Date().getFullYear(),
По умолчанию должен быть текущий год + 1

2020-12-18 07:57 UTC, maksim-kononov-csssr commented on src/pages/project/EditProjectPage.tsx
> +    yearStart: project.yearStart ?? new Date().getFullYear(),
<img width="953" alt="year" src="https://user-images.githubusercontent.com/45596310/102589027-748b2600-411f-11eb-81fb-170ac1fc58ce.png">

2020-12-21 11:06 UTC, Inzephirum commented on src/pages/project/EditProjectPage.tsx
> +    yearStart: project.yearStart ?? new Date().getFullYear(),
https://github.com/gpn-prototypes/vega-sp/pull/116 исправил тут. Сделал под фикс задачу. Этот ПР закрываю

2020-12-21 11:07 UTC, closed without merging