VEGA-834: Добавить data-test-id для текстов валидации
gpn-prototypes/vega-sp pull request #126
Opened 2021-01-11 11:56 UTC by hitmanet

Jira issue: VEGA-834

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: есть описание изменений или приложена ссылка на задачу с описанием, оставлены пояснительные комментарии к diff
- [ ] JS: нет предупреждений и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем PR
- [ ] Коммиты: проименованы в соответствии с [правилами](../docs/commits-style.md)

2021-01-11 12:03 UTC, c1n1k approved these changes

2021-01-11 13:46 UTC, fixmylie commented on src/ui/features/projects/ProjectForm/steps/DescriptionStep/DescriptionStep.tsx
> +          data-testid={errorTestId}
```suggestion
          data-testid={`${props['data-testid']}:error`}
```
И не нужно будет добавлять ещё один пропс и поддерживать его.

2021-01-11 15:58 UTC, c1n1k approved these changes

2021-01-11 16:01 UTC, c1n1k commented on src/ui/features/projects/ProjectForm/steps/DescriptionStep/DescriptionStep.tsx
> +          data-testid={errorTestId}
в таком случае придётся добавить проерку пропса иначе получим `:error` в любом случае, так что лучше проконтролировать пропс

2021-01-11 16:02 UTC, c1n1k commented
по какой причине пришлось изменить имя переменной?

2021-01-12 04:01 UTC, fixmylie commented on src/ui/features/projects/ProjectForm/steps/DescriptionStep/DescriptionStep.tsx
> +          data-testid={errorTestId}
Это да, а то получим `undefined:error`. Мое предложение было к тому, чтобы не плодить `testIDSomething`, а передать только один пропс и внутри сделать проверку и добавление остальных `testid`.

2021-01-12 04:02 UTC, fixmylie approved these changes

2021-01-12 04:02 UTC, fixmylie commented on src/ui/features/projects/ProjectForm/steps/DescriptionStep/DescriptionStep.tsx
> +          data-testid={`${testId}:error`}
лучше добавить проверку, а то получим `undefined:error`.

2021-01-12 09:09 UTC, maksim-kononov-csssr requested changes

2021-01-12 09:09 UTC, maksim-kononov-csssr commented on src/ui/features/projects/ProjectForm/steps/DescriptionStep/DescriptionStep.tsx
> +const testID = {
Самое хорошее решение - вынести компонент TextField в отдельный файл.
Более простое решение - переименовать переменную в компоненте TextField, там гораздо меньше нужно менять. И можно назвать localTestId или хоть _testId, но игра в замену регистра - no bueno

2021-01-13 14:17 UTC, hitmanet commented
@maksim-kononov-csssr глянь еще раз пожалуйста

2021-01-13 16:48 UTC, maksim-kononov-csssr approved these changes

2021-01-13 17:10 UTC, merged