VEGA-901: Рефакторинг автосейва в ProjectForm
gpn-prototypes/vega-sp pull request #168
Opened 2021-03-01 06:25 UTC by hitmanet

Jira issue: VEGA-901

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: есть описание изменений или приложена ссылка на задачу с описанием, оставлены пояснительные комментарии к diff
- [ ] JS: нет предупреждений и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем PR
- [ ] Коммиты: проименованы в соответствии с [правилами](../docs/commits-style.md)

2021-03-04 11:35 UTC, fixmylie approved these changes

2021-03-04 11:35 UTC, fixmylie commented on src/pages/project/RouteLeavingGuard.tsx
> +    // В другой вкладке было мерцание модалки. Добавил доп.проверку, чтобы его избежать
а почему такое мерцание происходит?

2021-03-04 11:35 UTC, fixmylie commented on src/ui/features/projects/ProjectForm/ProjectForm.test.tsx
> +    test.only('срабатывает повторное автосохранение', async () => {
only

2021-03-04 11:44 UTC, hitmanet commented on src/pages/project/RouteLeavingGuard.tsx
> +    // В другой вкладке было мерцание модалки. Добавил доп.проверку, чтобы его избежать
в эту часть кода не заходило, если код выполнялся в другой вкладке почему-то

2021-03-04 11:50 UTC, hitmanet commented on src/pages/project/RouteLeavingGuard.tsx
> +    // В другой вкладке было мерцание модалки. Добавил доп.проверку, чтобы его избежать
Потому что стейт менялся только в одной вкладке и когда в двух вкладках происходил переход с создания проекта на просмотр проекта, в одной из них не менялся стейт (здесь он приходит в пропе when) и на секунду показывалась модалка при переходе на нее

2021-03-04 11:52 UTC, hitmanet commented on src/ui/features/projects/ProjectForm/ProjectForm.test.tsx
> +    test.only('срабатывает повторное автосохранение', async () => {
поправил

2021-03-04 13:20 UTC, sergavshin requested changes

2021-03-04 13:20 UTC, sergavshin commented on src/ui/features/projects/ProjectForm/ProjectForm.test.tsx
> +    */
Компоненты, которые могут быть переиспользованы  лучше тестировать отдельно. То, что в форме есть - это тоже хорошо, но неплохо было бы иметь тесты на сам компонент. Тогда в будущем можно легко перенести этот компонент в другой модуль/проект

2021-03-04 13:20 UTC, sergavshin commented on src/ui/features/projects/ProjectForm/ProjectForm.test.tsx
> +    */
Можно не править. Это просто на случай, когда снова возникнет вопрос "где лучше сделать тест?"

2021-03-04 13:20 UTC, sergavshin commented on src/ui/features/projects/ProjectForm/AutosaveFormSpy.tsx
> +        prevActive.current = formState.active;
Это лучше сделать через `usePrevious`. Раньше не получалось так сделать, потому что это все на уровне формы рендерилось.

Сам `FromSpy` можно заменить на `useFormState`. Хук принимает все тоже самое, кроме `render` пропа. Тогда тут просто будет возвращаться `null`

2021-03-04 13:20 UTC, sergavshin commented on src/ui/features/projects/ProjectForm/AutosaveFormSpy.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
так и не получилось починить? Даже если `(keyof T)[]` заменить на `TriggeredFields<T>`, где `type TriggeredFields<T> = (keyof T)[]` ?

2021-03-04 13:20 UTC, sergavshin commented on src/pages/project/CreateProjectPage.tsx
> +        whiteRoutes={['/projects/show/:projectId', '/login']}
выглядит странно, потому что этот компонент в принципе не может на этих роутах отрисовываться

2021-03-04 13:20 UTC, sergavshin commented on src/pages/project/CreateProjectPage.tsx
> +        whiteRoutes={['/projects/show/:projectId', '/login']}
тут скорее нужно как-то обновлять `isNavigationBlocked`, если в другой вкладке блокировка изменилась

2021-03-04 13:25 UTC, hitmanet commented on src/pages/project/CreateProjectPage.tsx
> +        whiteRoutes={['/projects/show/:projectId', '/login']}
так передаются не роуты, на которых рендерится, а роуты, переход на которые не должен блочиться

2021-03-04 13:26 UTC, hitmanet commented on src/ui/features/projects/ProjectForm/AutosaveFormSpy.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
попробую

2021-03-04 13:35 UTC, hitmanet commented on src/ui/features/projects/ProjectForm/AutosaveFormSpy.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
не работает

2021-03-04 13:45 UTC, hitmanet commented on src/ui/features/projects/ProjectForm/AutosaveFormSpy.tsx
> +        prevActive.current = formState.active;
готово

2021-03-04 13:55 UTC, hitmanet commented on src/pages/project/CreateProjectPage.tsx
> +        whiteRoutes={['/projects/show/:projectId', '/login']}
я просто дополнил пример, который был с /login

2021-03-04 13:55 UTC, hitmanet commented on src/ui/features/projects/ProjectForm/ProjectForm.tsx
> +              autoSave={mode === 'create'}
исправил

2021-03-05 07:31 UTC, sergavshin commented on src/ui/features/projects/ProjectForm/Autosave.tsx
> +  }
почему только если `null` ? а если `save` перегенерится?

2021-03-05 07:31 UTC, sergavshin commented on src/ui/features/projects/ProjectForm/Autosave.tsx
> +  }
мож тут просто всегда присваивать?

2021-03-05 07:33 UTC, hitmanet commented on src/ui/features/projects/ProjectForm/Autosave.tsx
> +  }
хм
ты прав

2021-03-05 07:34 UTC, hitmanet commented on src/ui/features/projects/ProjectForm/AutosaveFormSpy.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Это видимо проблема из-за компонента-дженерика

2021-03-05 07:44 UTC, hitmanet commented on src/ui/features/projects/ProjectForm/Autosave.tsx
> +  }
@sergavshin исправил

2021-03-05 07:58 UTC, sergavshin approved these changes

2021-03-12 07:50 UTC, merged