VEGA-3434: Добавление сортировки списка проектов
gpn-prototypes/vega-sp pull request #186
Opened 2021-04-02 16:11 UTC by DmitriiBo

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: есть описание изменений или приложена ссылка на задачу с описанием, оставлены пояснительные комментарии к diff
- [ ] JS: нет предупреждений и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем PR
- [ ] Коммиты: проименованы в соответствии с [правилами](../docs/commits-style.md)

2021-04-05 10:09 UTC, lipgen approved these changes

2021-04-06 11:08 UTC, ijon requested changes
- надо убрать изменения, не принадлежащие теме данного PR 
- надо навести порядок с видами и направлениями сортировки

2021-04-06 11:08 UTC, ijon commented on src/pages/projects/ProjectsPage.tsx
> +        const orderBy = getSortOrder(sortingBy);
1. здесь точно не перепутаны sort order и sorting by? -- `sortBy <- sortOrder`, `orderBy <- 
sortingBy`?

2. в коде используется много названий одного и того же: sortBy-sortingBy-sortType для направления сортировки, orderBy-sortingBy-projectOrderBy для вида сортировки -- из-за этого путаница

Нужно выбрать и использовать одно наименование для одного понятия во всём коде -- тотально. Чтобы никаких переименований "функция так, переменная так, в третьем месте этак" не было вообще.
Хотя бы здесь в vega-sp.

(Хотя на самом деле нужно в коде всего проекта, во всех репозиториях).

2021-04-06 11:08 UTC, ijon commented on src/pages/projects/ProjectsPage.tsx
> +      ? totalQuantityProjects - (totalQuantityProjects - currentPageNumber * PAGE_SIZE)
Откуда берётся PAGE_SIZE? это константа? как и где она меняется?

2021-04-06 11:08 UTC, ijon commented on src/pages/projects/ProjectsTable/types.ts
> +export type SortByProps<T> = {
Повторяются определения, уже данные graphql-схемой, -- такое повторение необходимо? почему?

2021-04-06 14:36 UTC, DmitriiBo commented on src/pages/projects/ProjectsPage.tsx
> +import { ProjectOrderByEnum, SortType } from '../../__generated__/types';
А в `vega-sp` `schema.graphql` загружается автоматически через GraphQL Code Generator при локальном запуске проекта (конфиг для него в codegen.yaml) и что касается удаленных полей yearStart, yearEnd - это следствие такого обновления при загрузке... 

Получается она как раз уже берется из `vega2-back-core`. Переменная окружения `VEGA_SCHEMA_PATH` - указывает откуда стягивать схему, она и используюется в codegen.yaml

2021-04-06 14:37 UTC, DmitriiBo commented on src/pages/projects/ProjectsPage.tsx
> +      ? totalQuantityProjects - (totalQuantityProjects - currentPageNumber * PAGE_SIZE)
Константа задана непосредственно в модуле `ProjectsPage.tsx`, на данный момент никак не меняется

2021-04-06 14:39 UTC, DmitriiBo commented on src/pages/projects/ProjectsTable/types.ts
> +export type SortByProps<T> = {
Это определение для типизации данных, поступающих из компонента Table (от библиотеки компонентов consta)

2021-04-06 14:49 UTC, DmitriiBo commented on src/pages/projects/ProjectsPage.tsx
> +import { ProjectOrderByEnum, SortType } from '../../__generated__/types';
Использование `SortType` обусловлено тем, что параметр `sortBy` для запроса `projectList` в `sheme.graphql` типизирован через `SortType`, но `sortBy` из `user.customSettings` типизирован через SortTypeEnum (хотя они абсолютно идентичны), в следствие чего при попытке прокинуть в запрос на `projectList` данные из 
`sortBy: meData?.me?.customSettings?.projectList?.sortBy` мы получаем ошибку о не согласованности типов

2021-04-06 14:52 UTC, DmitriiBo commented on schema.graphql
> -  yearStart: Int
По этому пункту отписал ниже

2021-04-06 15:06 UTC, DmitriiBo commented on src/pages/projects/ProjectsPage.tsx
> +        const orderBy = getSortOrder(sortingBy);
Путаница возникла из за того, что в `vega2-back-core`  перепутаны названия --  в запросе `ProjectList` параметр `sortBy` принимает `'Asc' | 'Desc' `, а `orderBy` принимает название поля, а из компонента Table (от consta) мы получаем `sortingBy`:  _column_name_, sortOrder: 'asc | 'desc'

2021-04-06 15:32 UTC, ijon commented on src/pages/projects/ProjectsPage.tsx
> +import { ProjectOrderByEnum, SortType } from '../../__generated__/types';
> А в `vega-sp` `schema.graphql` загружается автоматически через GraphQL Code Generator при локальном запуске проекта (конфиг для него в codegen.yaml) и что касается удаленных полей yearStart, yearEnd - это следствие такого обновления при загрузке...
> 
> Получается она как раз уже берется из `vega2-back-core`. Переменная окружения `VEGA_SCHEMA_PATH` - указывает откуда стягивать схему, она и используюется в codegen.yaml

Во-первых, главное, что сейчас в PR есть изменения, которые никак к его теме не относятся -- PR в этом отношении "грязный" -- так быть не должно. И не важно, откуда и как эти изменения взялись (я надеюсь, локальный "запуск проекта" не делает автоматом коммиты? и локально обновлённые файлы не попадают автоматически в любой PR?).

Во-вторых, тогда `schema.graphql` -- результат кодогенерации, производный файл. Для кодогенерированных файлов есть две практики:
а) вообще не включать в состав исходных текстов проекта -- пусть генерируются при сборке
б) включать в состав исходных текстов в качестве кеша -- для экономии в случае, когда кодогенерация занимает большое время или требует сложных инструментов и/или настройки; при этом результат кодогенерации явно помещают в отдельное место -- как, в общем, здесь и сделано для собственно `__generated__/types.ts`; почему сделано исключение для `schema.graphql` -- непонятно (вернее понятно, что исторически он не был результатом кодогенерации, но эти-то времена уже прошли)
 
Мне кажется, что у нас не случай б), и никакие результаты кодогенерации мы могли бы под контролем версий не хранить.

2021-04-06 15:33 UTC, ijon commented on src/pages/projects/ProjectsPage.tsx
> +import { ProjectOrderByEnum, SortType } from '../../__generated__/types';
> Использование `SortType` обусловлено тем, что параметр `sortBy` для запроса `projectList` в `sheme.graphql` типизирован через `SortType`, но `sortBy` из `user.customSettings` типизирован через SortTypeEnum (хотя они абсолютно идентичны), в следствие чего при попытке прокинуть в запрос на `projectList` данные из
> `sortBy: meData?.me?.customSettings?.projectList?.sortBy` мы получаем ошибку о не согласованности типов

Вот это и надо исправить, свести всё к какому-то одному типу.

2021-04-06 15:38 UTC, ijon commented on src/pages/projects/ProjectsTable/types.ts
> +export type SortByProps<T> = {
Вопрос был: эти (или очень похожие) определения уже генерируются по graphql-схеме -- их нельзя использовать при работе с Table? -- сейчас есть определения в двух местах и все возможности их рассинхронизации.

2021-04-06 15:43 UTC, ijon commented on src/pages/projects/ProjectsPage.tsx
> +        const orderBy = getSortOrder(sortingBy);
Ок, тогда в коде явно показан комментарий ровно с таким пояснением.
(И, конечно, задача на изменение атрибутов `ProjectList`).

2021-04-06 15:47 UTC, ijon commented on src/pages/projects/ProjectsPage.tsx
> +      ? totalQuantityProjects - (totalQuantityProjects - currentPageNumber * PAGE_SIZE)
Не для исправления здесь, но ужас.
Все подобные параметры должны быть реально параметрами. Хотя бы для параметризации build time.

2021-04-06 15:59 UTC, DmitriiBo commented on src/pages/projects/ProjectsTable/types.ts
> +export type SortByProps<T> = {
Ага, понял вопрос правильно, но не дописал:
...использование типов сгенерированных по graphql схеме не подходит

2021-04-06 16:01 UTC, DmitriiBo commented on src/pages/projects/ProjectsPage.tsx
> +      ? totalQuantityProjects - (totalQuantityProjects - currentPageNumber * PAGE_SIZE)
Тогда зафиксирую это, создам задачку

2021-04-06 16:19 UTC, DmitriiBo commented on src/pages/projects/ProjectsPage.tsx
> +import { ProjectOrderByEnum, SortType } from '../../__generated__/types';
Принял, зафиксирую тоже, будет задачка на BE

2021-04-06 16:20 UTC, DmitriiBo commented on src/pages/projects/ProjectsPage.tsx
> +import { ProjectOrderByEnum, SortType } from '../../__generated__/types';
> > Использование `SortType` обусловлено тем, что параметр `sortBy` для запроса `projectList` в `sheme.graphql` типизирован через `SortType`, но `sortBy` из `user.customSettings` типизирован через SortTypeEnum (хотя они абсолютно идентичны), в следствие чего при попытке прокинуть в запрос на `projectList` данные из
> > `sortBy: meData?.me?.customSettings?.projectList?.sortBy` мы получаем ошибку о не согласованности типов
> 
> Вот это и надо исправить, свести всё к какому-то одному типу.

Принял, зафиксирую тоже, будет задачка на BE

2021-04-06 16:21 UTC, DmitriiBo commented on src/pages/projects/ProjectsPage.tsx
> +        const orderBy = getSortOrder(sortingBy);
Прикреплю к общей задаче для BE на корректировку типов

2021-04-06 16:24 UTC, DmitriiBo commented on src/pages/projects/ProjectsPage.tsx
> +import { ProjectOrderByEnum, SortType } from '../../__generated__/types';
Тогда откачу изменения `schema.graphql`, и получается в этом же ПР добавить ее в .gitignore?

2021-04-07 13:31 UTC, ijon commented on src/pages/projects/ProjectsPage.tsx
> +import { ProjectOrderByEnum, SortType } from '../../__generated__/types';
Самый чистый вариант: 
1. в этом PR -- откатить изменения `schema.graphql` и ничего больше с ним не делать
2. в другом PR -- удалить `schema.graphql` и внести в `.gitignore`

Пункт 2 можно отдать кому-нибудь другому.

2021-04-07 13:35 UTC, ijon commented on src/pages/projects/ProjectsTable/types.ts
> +export type SortByProps<T> = {
Не замечание, но вопрос -- почему не подходят? и можно ли подходящие типы получать кодогенерацией, а не ручным писанием дублей?

2021-04-08 11:12 UTC, DmitriiBo commented on src/pages/projects/ProjectsTable/types.ts
> +export type SortByProps<T> = {
Думаю сейчас это возможно во множестве случаев, но не во всех. Нужно согласование регистров, названий свойств. Наверное, это можно было бы вынести в отдельную задачу

2021-04-08 11:26 UTC, ijon approved these changes

2021-04-08 11:30 UTC, merged