VEGA-407: Интеграция с бэком "Просмотр и редактирование проекта"
gpn-prototypes/vega-sp pull request #57
Opened 2020-11-09 07:07 UTC by maksim-kononov-csssr

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: есть описание изменений или приложена ссылка на задачу с описанием, оставлены пояснительные комментарии к diff
- [ ] JS: нет предупреждений и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем PR
- [ ] Коммиты: проименованы в соответствии с [правилами](../docs/commits-style.md)

2020-11-10 15:34 UTC, c1n1k commented on src/App/index.tsx
> +/*
в чем смысл комментария?

2020-11-10 15:40 UTC, c1n1k commented on src/App/index.tsx
> +/*
ты хотел вся всех типов сделать ключевым полем `vid`?

2020-11-10 15:45 UTC, c1n1k commented on src/pages/project/EditProjectPage.tsx
> +    data: queryProjectData,
кажестя приставка `query` лишняя

2020-11-10 15:47 UTC, c1n1k commented on src/pages/project/EditProjectPage.tsx
>      console.log('handleFormSubmit', values);
можно удалить уже?

2020-11-10 15:57 UTC, c1n1k approved these changes

2020-11-10 15:59 UTC, c1n1k commented
@maksim-kononov-csssr конфликты

2020-11-11 06:59 UTC, hitmanet approved these changes

2020-11-12 06:28 UTC, maksim-kononov-csssr commented on src/pages/project/EditProjectPage.tsx
> +    data: queryProjectData,
Страница и потом таблица посвящена созданию проекта, множество названий связанных со словом project и на мой взгляд так проще однозначно определить, что это ответ с данными на запрос по конкретному проекту

2020-11-12 06:29 UTC, maksim-kononov-csssr commented on src/pages/project/EditProjectPage.tsx
>      console.log('handleFormSubmit', values);
Перед демо удалю такие выводы

2020-11-12 06:30 UTC, maksim-kononov-csssr commented on src/App/index.tsx
> +/*
Да. Аполло клиент по умолчанию считает что можно идентифицировать объекты по полю id, а у нас vid. И вот таким образом можно его настроить смотреть на vid

2020-11-12 06:58 UTC, fixmylie approved these changes

2020-11-12 07:04 UTC, maksim-kononov-csssr commented on src/pages/project/CreateProjectPage.tsx
> +import { useCreateProject, useQueryRegionList, useUpdateProject2 } from './__generated__/project';
useUpdateProject2 - потому что в файле `src/pages/projects/projects.graphql` Рома тоже добавил мутацию UpdateProject. При генерации методов ошибка говорит что не может быть два запроса с одним названием

2020-11-12 07:05 UTC, maksim-kononov-csssr commented on src/pages/project/CreateProjectPage.tsx
> +import { useCreateProject, useQueryRegionList, useUpdateProject2 } from './__generated__/project';
Пока добавил useUpdateProject**2** потом подумаю как можно разграничить

2020-11-12 07:08 UTC, fixmylie commented on src/pages/project/CreateProjectPage.tsx
> +import { useCreateProject, useQueryRegionList, useUpdateProject2 } from './__generated__/project';
О как, надо тогда подумать над нэймингом. Создадим задачу на техдолг тогда?

2020-11-12 07:14 UTC, fixmylie requested changes

2020-11-12 07:14 UTC, fixmylie commented on src/pages/projects/ProjectsPage.tsx
> +    const name = (
тэкс. А зачем тут линк?
Я в своей задаче сделал так, чтобы можно было по клику на строку переходить к проекту

2020-11-12 07:15 UTC, Inzephirum commented on src/pages/project/CreateProjectPage.tsx
> +import { useCreateProject, useQueryRegionList, useUpdateProject2 } from './__generated__/project';
надо сделать, чтобы каждая страница лежала в своей папке, со своими мутациями, тогда не будет такой проблемы.

2020-11-12 07:17 UTC, fixmylie commented on src/pages/project/CreateProjectPage.tsx
> +import { useCreateProject, useQueryRegionList, useUpdateProject2 } from './__generated__/project';
так вроде так и сделано. Моя путация лежит в папке `projects`, а здесь `project`

2020-11-12 07:18 UTC, c1n1k commented on src/pages/project/CreateProjectPage.tsx
> +  }, [createProject]);
как странно это всё выглядит, в чем причина такаого решения?

2020-11-12 07:18 UTC, fixmylie commented on src/pages/projects/ProjectsPage.tsx
> +    const name = (
Думаю нужно оставить как было, а переход я сделал у себя в задаче

2020-11-12 07:21 UTC, c1n1k commented on src/pages/project/EditProjectPage.tsx
> +    data: queryProjectData,
когда есть `query` я предполагаю это это документ gql запроса, а не результат его выполнения

2020-11-12 07:23 UTC, hitmanet approved these changes

2020-11-12 07:23 UTC, hitmanet commented on src/pages/project/project.graphql
>  }
Может все-таки вынесем отсюда часть с регионами? А то большой файл получается

2020-11-12 07:23 UTC, hitmanet commented on src/ui/features/projects/ProjectForm/Banner.tsx
> +import { ReferenceDataType } from '../../../../pages/project/types';
а мы алиасы не настроили еще?

2020-11-12 07:24 UTC, maksim-kononov-csssr commented on src/pages/project/CreateProjectPage.tsx
> +  }, [createProject]);
в useEffect нельзя напрямую добавить асинхронную функцию, т.е. функция на строчке 27 не может быть объявлена асинхронной, но внутри этой функции можно вызывать асинхронную функцию

2020-11-12 07:26 UTC, maksim-kononov-csssr commented on src/pages/project/CreateProjectPage.tsx
> +  }, [createProject]);
если вопрос почему я вообще асинхронную функцию решил использовать - так наиболее явно можно разложить логику на два if: если в теле ответа все ок и если там ошибка

2020-11-12 07:28 UTC, maksim-kononov-csssr commented on src/pages/project/CreateProjectPage.tsx
> +  }, [createProject]);
как альтернатива - использовать метод onCompleted на самом хуке useCreateProject. Не знаю какой тут best practice, сделал как показалось более понятным

2020-11-12 07:29 UTC, maksim-kononov-csssr commented on src/pages/projects/ProjectsPage.tsx
> +    const name = (
Удалил

2020-11-12 07:32 UTC, maksim-kononov-csssr commented on src/pages/project/project.graphql
>  }
Я сделаю для себя заметку, но сейчас не понятно какая структура файловая будет удобней. Когда будут еще места где например будет запрос регионов - можно будет переместить

2020-11-12 07:38 UTC, fixmylie approved these changes

2020-11-12 07:41 UTC, Inzephirum commented on src/pages/project/CreateProjectPage.tsx
> +        setBlankProjectId(projectId);
может быть ошибка, если компонент на момент вызова функции будет уже размонтирован

2020-11-12 07:41 UTC, Inzephirum commented on src/pages/project/CreateProjectPage.tsx
> +    console.log(createProjectError, updateProjectError, queryRegionListError);
```suggestion
    console.log({ createProjectError, updateProjectError, queryRegionListError });
```
можно так сделать, тогда в консоли будет проще понять какая именно ошибка произошла, а какие нет

2020-11-12 07:41 UTC, Inzephirum commented on src/pages/project/EditProjectPage.tsx
> +        version: version || 0,
а бэк поймет `version: 0` ?

2020-11-12 07:41 UTC, Inzephirum commented on src/ui/features/projects/ProjectForm/Banner.tsx
> +  region: string | undefined,
```suggestion
  regionVid: string | undefined,
```
кажется более читаемым

2020-11-12 07:42 UTC, Inzephirum commented on src/ui/features/projects/ProjectForm/Banner.tsx
> +import { ReferenceDataType } from '../../../../pages/project/types';
Тут лучше решить структурой папок. Общие компоненты не должны импортировать типы из страниц, на которых они используются

2020-11-12 07:43 UTC, Inzephirum commented on src/pages/project/project.graphql
>  }
да кажется норм

2020-11-12 07:43 UTC, Inzephirum commented on src/pages/project/CreateProjectPage.tsx
> +import { useCreateProject, useQueryRegionList, useUpdateProject2 } from './__generated__/project';
ага, понял, странно

2020-11-12 07:47 UTC, hitmanet commented on src/pages/project/project.graphql
>  }
я просто боюсь, что будет разрастаться

2020-11-12 07:54 UTC, maksim-kononov-csssr commented on src/pages/project/EditProjectPage.tsx
> +    data: queryProjectData,
Да, справедливо🤔

2020-11-12 08:11 UTC, c1n1k commented on src/pages/project/CreateProjectPage.tsx
> +  }, [createProject]);
мутация сама по себе асинхронна же, и возвращает объект с данными, ошибкой зачем тебе понадобилось, выстраивать такую логику?

2020-11-12 08:27 UTC, maksim-kononov-csssr commented on src/ui/features/projects/ProjectForm/Banner.tsx
> +  region: string | undefined,
Согласен. Исправил

2020-11-12 08:38 UTC, maksim-kononov-csssr commented on src/pages/project/EditProjectPage.tsx
> +        version: version || 0,
В ответе на запрос проекта мы должны получить версию. Но в схеме это поле обозначено как необязательное, поэтому такие выражения нужны для TS

2020-11-12 08:40 UTC, maksim-kononov-csssr commented on src/pages/project/CreateProjectPage.tsx
> +    console.log(createProjectError, updateProjectError, queryRegionListError);
Исправил

2020-11-12 08:47 UTC, maksim-kononov-csssr commented on src/pages/project/CreateProjectPage.tsx
> +        setBlankProjectId(projectId);
Добавил проверку

2020-11-12 08:53 UTC, maksim-kononov-csssr commented on src/ui/features/projects/ProjectForm/Banner.tsx
> +import { ReferenceDataType } from '../../../../pages/project/types';
Тут нет циклической зависимости, если ты об этом. Один и тот же тип нужен и на странице и в дочернем компоненте, тип лежит в отдельном файле в папке со страницей. Куда в таком случае лучше положить общие типы?

2020-11-12 09:23 UTC, c1n1k approved these changes

2020-11-12 10:53 UTC, merged