VEGA-576: Доработки для авторизации и аутентификации
gpn-prototypes/vega-sp pull request #89
Opened 2020-12-07 15:07 UTC by maksim-kononov-csssr

Jira issue: VEGA-576

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: есть описание изменений или приложена ссылка на задачу с описанием, оставлены пояснительные комментарии к diff
- [ ] JS: нет предупреждений и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем PR
- [ ] Коммиты: проименованы в соответствии с [правилами](../docs/commits-style.md)

2020-12-07 15:23 UTC, hitmanet approved these changes

2020-12-07 15:43 UTC, c1n1k commented on src/pages/project/CreateProjectPage.tsx
> +        type: values.type,
уже можно удалить

2020-12-07 15:44 UTC, c1n1k requested changes
удали типы

2020-12-07 15:54 UTC, mxmknnv commented on src/pages/project/CreateProjectPage.tsx
> +        type: values.type,
на ветке бекенда с авторизацией немного старая схема и там нужен тип проекта

2020-12-07 15:55 UTC, maksim-kononov-csssr commented on src/pages/project/CreateProjectPage.tsx
> +        type: values.type,
на ветке бекенда с авторизацией немного старая схема и там нужен тип проекта

2020-12-08 05:32 UTC, fixmylie approved these changes

2020-12-08 05:32 UTC, fixmylie commented on src/pages/project/CreateProjectPage.tsx
> +        type: values.type,
А есть информация, когда нужна фича ветка попадёт в какой-то интегрейшн?
Велик шанс, что этот коммент тут и останется по итогу. И ещё получается, что мы эту ветку не сможем влить до определенного момента, пока бэк не смержит свою...

2020-12-08 05:32 UTC, fixmylie commented on src/pages/project/CreateProjectPage.tsx
> +        type: values.type,
И насколько это пр будет актуальный, если бэк вмержит ветку с авторизацией? По моему тут никаких изменений не нужно будет.

2020-12-08 05:33 UTC, fixmylie requested changes
+ за типы.
Этот ПР по сути нужен, чтобы просто корректно протестировать данную фичу в текущей ситуации? чтобы к вега-шелл можно было подключить вега-сп?

2020-12-08 07:49 UTC, maksim-kononov-csssr commented on src/pages/project/CreateProjectPage.tsx
> +        type: values.type,
Да, тут ничего не менялось по задаче. Только для того, чтобы можно было протестировать задачу, прогнать полный цикл по созданию проекта против текущей версии бека. Вливать ее по настоящему в релиз не нужно

2020-12-08 07:50 UTC, maksim-kononov-csssr commented
> '+' за типы.
> Этот ПР по сути нужен, чтобы просто корректно протестировать данную фичу в текущей ситуации? чтобы к вега-шелл можно было подключить вега-сп?

Да, так и есть

2020-12-08 09:39 UTC, c1n1k commented
схема же уже обновлена, и в сп были проблемы из-за этого поля на прошлой неделе

2020-12-08 11:57 UTC, maksim-kononov-csssr commented
> схема же уже обновлена, и в сп были проблемы из-за этого поля на прошлой неделе

Да, именно так. На той верси бека, где сделана авторизация сохранилась старая версия схемы. Чтобы на стенде все собралось и работало я указываю эту ветку, если укажу релиз ветку - будут ошибки. Этот PR не нужно добавлять. В теории, когда бек вольет авторизацию на интеграционный стенд там будет новая схема и все заработает.

2020-12-08 13:04 UTC, maksim-kononov-csssr commented
Бекенд разработчик обновил ветку, теперь этот PR и ветка на vega-sp не нужена

2020-12-08 13:04 UTC, closed without merging